# -*- coding: utf-8 -*-
"""sentiment_analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oOwzAJv8ituKA2FtQb9IWW_UFCbb8uBI
"""

# -----------------------------
# 1. Install required packages
# -----------------------------
!pip install spacytextblob
!python -m textblob.download_corpora
!python -m spacy download en_core_web_md

# -----------------------------
# 2. Import libraries
# -----------------------------
import pandas as pd
import spacy
from spacytextblob.spacytextblob import SpacyTextBlob
from google.colab import files

# -----------------------------
# 3. Upload CSV dataset
# -----------------------------
uploaded = files.upload()  # Upload your CSV file here
filename = list(uploaded.keys())[0]

# Load CSV into DataFrame
data = pd.read_csv(filename)

# Inspect dataset
print("First 5 rows of dataset:")
print(data.head())

# Select 'reviews.text' column and remove missing values
reviews_data = data['reviews.text']
clean_data = reviews_data.dropna().reset_index(drop=True)
print(f"\nTotal reviews after removing missing values: {len(clean_data)}")

# -----------------------------
# 4. Load spaCy model
# -----------------------------
nlp = spacy.load("en_core_web_md")
nlp.add_pipe("spacytextblob")

# -----------------------------
# 5. Preprocess text
# -----------------------------
def preprocess_text(text):
    """
    Cleans the text:
    - Converts to lowercase
    - Strips whitespace
    - Removes stop words
    - Keeps only alphabetic tokens
    """
    doc = nlp(text.lower().strip())
    tokens = [token.text for token in doc if not token.is_stop and token.is_alpha]
    return " ".join(tokens)

# Apply preprocessing
clean_data = clean_data.apply(preprocess_text)

# Show sample preprocessed reviews
print("\nSample preprocessed reviews:")
print(clean_data.sample(5, random_state=42))

# -----------------------------
# 6. Sentiment analysis function
# -----------------------------
def get_sentiment(review):
    """
    Returns the polarity score and sentiment label of a product review.
    """
    doc = nlp(review)
    polarity = doc._.blob.polarity

    if polarity > 0:
        sentiment = "Positive"
    elif polarity < 0:
        sentiment = "Negative"
    else:
        sentiment = "Neutral"

    return polarity, sentiment

# -----------------------------
# 7. Test sentiment on sample reviews
# -----------------------------
sample_reviews = clean_data.sample(5, random_state=42)

print("\nSentiment analysis on sample reviews:")
for review in sample_reviews:
    polarity, sentiment = get_sentiment(review)
    print(f"Review: {review}\nPolarity: {polarity}, Sentiment: {sentiment}\n")

# -----------------------------
# 8. Optional: review similarity
# -----------------------------
review1 = clean_data.iloc[0]
review2 = clean_data.iloc[1]

doc1 = nlp(review1)
doc2 = nlp(review2)

similarity_score = doc1.similarity(doc2)
print(f"Similarity between first two reviews: {similarity_score:.2f}")

# -----------------------------
# 9. Sentiment distribution for all reviews
# -----------------------------
sentiment_counts = clean_data.apply(lambda x: get_sentiment(x)[1]).value_counts()
print("\nSentiment counts in dataset:")
print(sentiment_counts)

# -----------------------------
# 10. Save results to CSV
# -----------------------------
results = clean_data.apply(lambda x: get_sentiment(x))
results_df = pd.DataFrame(results.tolist(), columns=['Polarity', 'Sentiment'])

final_df = pd.concat([clean_data, results_df], axis=1)
final_df.to_csv("amazon_reviews_sentiment.csv", index=False)
print("\nSentiment analysis results saved to 'amazon_reviews_sentiment.csv'")